### ISSUE TITLE
Does it work well with Twitter Bootstrap?

### ISSUE THREAD

**Issue by isuhendro** [forcedotcom/scrollerjs#30]
For existing project using Twitter bootstrap, i found scrollerjs default behaviour that trying to add `scroller-wrapper` CSS class having `overflow: hidden` is conflicting with Twitter bootstrap `fluid layout`

``` javascript
            this.wrapper.classList.add('scroller-wrapper');
```

``` CSS
.scroller-wrapper {
    position: relative;
    overflow: hidden;
}
```

The outcome is the list of elements inside the wrapper (that actually overflow getting hidden), and to resolve it i need to remove `overflow:hidden` style.
I suspect I would break existing scrollerjs library one way or the other, is there any suggestion?
